name: Basic CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, edited]

env:
  GO111MODULE: "on"

jobs:
  lint:
    name: GoLang CI linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.18
          cache: true

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.47.3
  test:
    name: GoLang CI linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.18
          cache: true

      - name: Tests
        run: go test -v -count=1 -race -timeout=1m ./...
